decks:
- name: devdeck.decks.single_page_deck_controller.SinglePageDeckController
  serial_number: DL30K1A78181
  settings:
    controls:
    - name: devdeck.controls.clock_control.ClockControl
      key: 0
    # Column for shelve light
    - name: devdeck_hue.toggle.Toggle
      key: 2
      settings:
        host: 192.168.1.241
        light_id: 1
    - name: devdeck_hue.brightness.Increase
      key: 7
      settings:
        host: 192.168.1.241
        light_id: 1
        step: 25
    - name: devdeck_hue.brightness.Decrease
      key: 12
      settings:
        host: 192.168.1.241
        light_id: 1
        step: 25
    # Column for overhead light
    - name: devdeck_hue.toggle.Toggle
      key: 3
      settings:
        host: 192.168.1.241
        light_id: 4
    - name: devdeck_hue.brightness.Increase
      key: 8
      settings:
        host: 192.168.1.241
        light_id: 4
        step: 25
    - name: devdeck_hue.brightness.Decrease
      key: 13
      settings:
        host: 192.168.1.241
        light_id: 4
        step: 25
    # Column for elgato
    - name: devdeck_key_light.key_light_toggle_control.KeyLightToggleControl
      key: 4
      settings:
        host: 192.168.1.240
    - name: devdeck_key_light.brightness.Increase
      key: 9
      settings:
        host: 192.168.1.240
        step: 10
    - name: devdeck_key_light.brightness.Decrease
      key: 14
      settings:
        host: 192.168.1.240
        step: 10
