[".config/git/ignore"]
    type = "file"
    url = "https://www.toptal.com/developers/gitignore/api/linux,visualstudiocode,vim,python,macos"
    refreshPeriod = "744h"  # 31d
{{ if (eq .chezmoi.hostname "jonsnow") }}
# renovate: depName=grafana/mimir datasource=github-releases
{{ $currentMimirVersion := "mimir-2.2.0" -}}
[".local/bin/mimirtool"]
    type = "file"
    url = "https://github.com/grafana/mimir/releases/download/{{$currentMimirVersion}}/mimirtool-{{.chezmoi.os}}-{{.chezmoi.arch}}"
    executable = true
    refreshPeriod = "744h"  # 31d
{{ end }}
{{ if (and (eq .chezmoi.os "linux") (not .headless) (ne .chezmoi.username "root")) -}}
# renovate: depName=ryanoasis/nerd-fonts datasource=github-releases
{{ $currentNerdfontsVersion := "v2.1.0" -}}
{{ $fontsDir := .fontsdir -}}
{{ $fonts := list "CascadiaCode" "DejaVuSansMono" "Hack" "Meslo" -}}
{{ range $fonts }}
["{{ $fontsDir }}/{{ . }}"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/{{$currentNerdfontsVersion}}/{{.}}.zip"
{{ end }}
{{ end -}}
[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
["code/byobu"]  # .tmux.conf references to files there
    type = "git-repo"
    url = "https://github.com/dustinkirkland/byobu.git"
    refreshPeriod = "168h"
["irssi/scripts/autorun/adv_windowlist.pl"]
    type = "file"
    url = "https://raw.githubusercontent.com/irssi/scripts.irssi.org/master/scripts/adv_windowlist.pl"
    refreshPeriod = "168h"
